name: "Semantic Versioning"
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run lint

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - run: npm install
#      - run: npm run test

  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Label check
        uses: ./
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}